name       : convertall
version    : 0.7.2
release    : 1
source     :
    - https://pilotfiber.dl.sourceforge.net/project/convertall/0.7.2/convertall-0.7.2.tar.gz : 9d465d12fbb45f88359b1d80619658143b203014157f65843917c1f63337c8a4
license    : GPL-2.0
component  : office.maths
summary    : ConvertAll is yet another unit converter. But it can combine the units any way you want.
description: |
    With ConvertAll, you can combine the units any way you want. 
    If you want to convert from inches per decade, that's fine. 
    Or from meter-pounds. Or from cubic nautical miles. 
    The units don't have to make sense to anyone else.
builddeps  :
    - python3-qt5
rundeps    :
    - python3-qt5
install    : |
    python3 install.py -p /usr -i /usr/share/pixmaps/convertall -b $installdir
    rm -fr $installdir/usr/share/convertall/__pycache__/

    install -D -m 00644 $pkgfiles/convertall.desktop $installdir/usr/share/applications/convertall.desktop
