name       : convertall
version    : 0.7.3
release    : 2
source     :
    - http://sourceforge.net/projects/convertall/files/0.7.3/convertall-0.7.3.tar.gz : 1228cb1f1def6e1d72d96c75c7d1e4df406625c84bc52eaa530773e35410ff39
license    : GPL-2.0
component  : office.maths
summary    : ConvertAll is yet another unit converter. But it can combine the units any way you want.
description: | 
    With ConvertAll, you can combine the units any way you want. 
    If you want to convert from inches per decade, that's fine. 
    Or from meter-pounds. Or from cubic nautical miles. 
    The units don't have to make sense to anyone else.
builddeps  :
    - python3-qt5
rundeps    :
    - python3-qt5
install    : |
    python3 install.py -p /usr -i /usr/share/pixmaps/convertall -b $installdir
    rm -fr $installdir/usr/share/convertall/__pycache__/

    install -D -m 00644 $pkgfiles/convertall.desktop $installdir/usr/share/applications/convertall.desktop
