name       : convertall
version    : 0.7.4
release    : 3
source     :
    - https://jaist.dl.sourceforge.net/project/convertall/0.7.4/convertall-0.7.4.tar.gz : 7f11d4db064c3980b25bd1b5b785ed334fa5e3067e8d9ef437bbcb96e2408d04
license    : GPL-2.0-or-later
component  : office.maths
summary    : ConvertAll is yet another unit converter. But it can combine the units any way you want.
description: |
    With ConvertAll, you can combine the units any way you want. If you want to convert from inches per decade, that's fine. Or from meter-pounds. Or from cubic nautical miles. The units don't have to make sense to anyone else.
builddeps  :
    - python3-qt5
rundeps    :
    - python3-qt5
install    : |
    python3 install.py -p /usr -i /usr/share/pixmaps/convertall -b $installdir
    rm -fr $installdir/usr/share/convertall/__pycache__/
